# Generated by Django 4.1.7 on 2023-03-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-01-01'),
            preserve_default=False,
        ),
    ]
